[package]
name = "cryptic"
version = "0.1.0"
authors = ["Giorgos Georgiou <giorgos.georgiou@outlook.com>"]

[dependencies]
ring = "0.11.0"
rand = "0.3.15"
rpassword = "0.4.0"
yaml-rust = "0.3.5"

[dependencies.clap]
version = "2.25.0"
features = ["yaml", "suggestions", "color"]
